package constants

const (
	METHOD_PHONE         = "phone"
	METHOD_EMAIL         = "email"
	ACTION_SIGNIN        = "signin"
	ACTION_SIGNUP        = "signup"
	ACTION_SIGN_CONTRACT = "sign_contract"
	ACTION_CHANGE        = "change"
	ACTION_RESET         = "reset"
	STATUS_PENDING       = "pending"
	STATUS_CANCELLED     = "cancelled"
	STATUS_REMOVED       = "removed"
	STATUS_FAIL          = "fail"
	STATUS_SUCCESS       = "success"
	STATUS_SIGNED        = "signed"
	STATUS_PAID          = "paid"
	STATUS_ACTIVE        = "active"
	STATUS_NOACTIVE      = "noactive"
	STATUS_DISABLED      = "disabled"
	STATUS_DRAFT         = "draft"
	CATEGORY_AVATAR      = "avatar"
	CATEGORY_PHOTO       = "photo"
	CATEGORY_DOCUMENT    = "document"
)
