// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Alert struct {
	AlertID       int    `json:"AlertID"`
	AssetID       int    `json:"AssetID"`
	Price         string `json:"Price"`
	TimestampOpen int    `json:"TimestampOpen"`
}

type Appointment struct {
	AppointmentID    int     `json:"AppointmentID"`
	Type             *string `json:"Type"`
	Title            *string `json:"Title"`
	Description      *string `json:"Description"`
	DateCreated      *string `json:"DateCreated"`
	TimestampCreated *int    `json:"TimestampCreated"`
	DateDue          *string `json:"DateDue"`
	TimestampDue     *int    `json:"TimestampDue"`
	Status           *string `json:"Status"`
	LeadID           *int    `json:"LeadID"`
}

type Balance struct {
	BalanceID      int     `json:"BalanceID"`
	MemberID       *int    `json:"MemberID"`
	CurrencyID     *int    `json:"CurrencyID"`
	Amount         *string `json:"Amount"`
	AmountNegative *bool   `json:"AmountNegative"`
}

type BankDetails struct {
	BankDetailsID          *int    `json:"BankDetailsID"`
	Title                  *string `json:"Title"`
	BeneficiaryCompany     *string `json:"BeneficiaryCompany"`
	BeneficiaryFirstName   *string `json:"BeneficiaryFirstName"`
	BeneficiaryLastName    *string `json:"BeneficiaryLastName"`
	BeneficiaryCountry     *string `json:"BeneficiaryCountry"`
	BeneficiaryCity        *string `json:"BeneficiaryCity"`
	BeneficiaryZip         *string `json:"BeneficiaryZip"`
	BeneficiaryAddress     *string `json:"BeneficiaryAddress"`
	BankName               *string `json:"BankName"`
	BankBranch             *string `json:"BankBranch"`
	BankIfsc               *string `json:"BankIFSC"`
	BankBranchCountry      *string `json:"BankBranchCountry"`
	BankBranchCity         *string `json:"BankBranchCity"`
	BankBranchZip          *string `json:"BankBranchZip"`
	BankBranchAddress      *string `json:"BankBranchAddress"`
	BankAccountNumber      *string `json:"BankAccountNumber"`
	BankAccountType        *string `json:"BankAccountType"`
	BankRoutingNumber      *string `json:"BankRoutingNumber"`
	BankTransferCaption    *string `json:"BankTransferCaption"`
	BankIban               *string `json:"BankIBAN"`
	BankSwift              *string `json:"BankSWIFT"`
	BankSWIFTCorrespondent *string `json:"BankSWIFTCorrespondent"`
	BankBic                *string `json:"BankBIC"`
}

type Campaign struct {
	CampaignID       int     `json:"CampaignID"`
	Title            *string `json:"Title"`
	Description      *string `json:"Description"`
	DateCreated      *string `json:"DateCreated"`
	TimestampCreated *int    `json:"TimestampCreated"`
}

type Category struct {
	CategoryID int    `json:"CategoryID"`
	Title      string `json:"Title"`
}

type Checklist struct {
	ChecklistID      int     `json:"ChecklistID"`
	Title            *string `json:"Title"`
	Complete         *bool   `json:"Complete"`
	Position         *int    `json:"Position"`
	DateCreated      *string `json:"DateCreated"`
	TimestampCreated *int    `json:"TimestampCreated"`
	LeadID           *int    `json:"LeadID"`
}

type Code struct {
	Code string `json:"code"`
}

type Comment struct {
	CommentID        int     `json:"CommentID"`
	MemberID         *int    `json:"MemberID"`
	Content          *string `json:"Content"`
	DateCreated      *string `json:"DateCreated"`
	TimestampCreated *int    `json:"TimestampCreated"`
	DateEdited       *string `json:"DateEdited"`
	TimestampEdited  *int    `json:"TimestampEdited"`
	LeadID           *int    `json:"LeadID"`
}

type Contract struct {
	ContractID int     `json:"ContractID"`
	Title      string  `json:"Title"`
	Content    *string `json:"Content"`
	ContentRaw *string `json:"ContentRaw"`
	OfferID    *int    `json:"OfferID"`
	Current    *bool   `json:"Current"`
	Template   *bool   `json:"Template"`
}

type CreationResponse struct {
	RecordID int `json:"RecordID"`
}

type Currency struct {
	CurrencyID int    `json:"CurrencyID"`
	Title      string `json:"Title"`
	Symbol     string `json:"Symbol"`
}

type Deal struct {
	DealID            int     `json:"DealID"`
	OfferID           *int    `json:"OfferID"`
	ContractID        *int    `json:"ContractID"`
	MemberID          *int    `json:"MemberID"`
	CurrencyID        *int    `json:"CurrencyID"`
	SignatureFilename *string `json:"SignatureFilename"`
	SignatureURL      *string `json:"SignatureURL"`
	VerificationCode  *string `json:"VerificationCode"`
	DateCreated       *string `json:"DateCreated"`
	DateSigned        *string `json:"DateSigned"`
	DateVerified      *string `json:"DateVerified"`
	DatePaid          *string `json:"DatePaid"`
	DateStart         *string `json:"DateStart"`
	DateEnd           *string `json:"DateEnd"`
	Status            *string `json:"Status"`
	Amount            *string `json:"Amount"`
	Duration          *string `json:"Duration"`
}

type DragRequest struct {
	Position []int `json:"Position"`
}

type Faq struct {
	Faqid    int     `json:"FAQID"`
	Question *string `json:"Question"`
	Answer   *string `json:"Answer"`
	Position *int    `json:"Position"`
}

type Info struct {
	MemberID      int    `json:"MemberID"`
	Event         string `json:"Event"`
	ID            int    `json:"ID"`
	Value         string `json:"Value"`
	Rate          string `json:"Rate"`
	RateBuy       string `json:"RateBuy"`
	RateSell      string `json:"RateSell"`
	Change        string `json:"Change"`
	Sentiment     int    `json:"Sentiment"`
	SentimentType string `json:"SentimentType"`
}

type Interest struct {
	InterestID   int     `json:"InterestID"`
	OfferID      *int    `json:"OfferID"`
	AmountFrom   *string `json:"AmountFrom"`
	AmountTo     *string `json:"AmountTo"`
	DurationFrom *string `json:"DurationFrom"`
	DurationTo   *string `json:"DurationTo"`
	Interest     *string `json:"Interest"`
}

type Invest struct {
	InvestID      int      `json:"InvestID"`
	OfferID       *int     `json:"OfferID"`
	CategoryID    *int     `json:"CategoryID"`
	CurrencyID    *int     `json:"CurrencyID"`
	BankDetailsID *int     `json:"BankDetailsID"`
	Title         *string  `json:"Title"`
	Subtitle      *string  `json:"Subtitle"`
	Description   *string  `json:"Description"`
	Faq           []*Faq   `json:"FAQ"`
	Photo         []*Media `json:"Photo"`
	Document      []*Media `json:"Document"`
	Status        *string  `json:"Status"`
}

type Invoice struct {
	InvoiceID        int     `json:"InvoiceID"`
	OfferID          *int    `json:"OfferID"`
	MemberID         *int    `json:"MemberID"`
	DealID           *int    `json:"DealID"`
	CurrencyID       *int    `json:"CurrencyID"`
	Status           *string `json:"Status"`
	Amount           *string `json:"Amount"`
	DateCreated      *string `json:"DateCreated"`
	TimestampCreated *int    `json:"TimestampCreated"`
	DatePaid         *string `json:"DatePaid"`
	TimestampPaid    *int    `json:"TimestampPaid"`
}

type InvoiceSendToEmailRequest struct {
	InvoiceID int    `json:"InvoiceID"`
	Email     string `json:"Email"`
}

type Lead struct {
	LeadID           int     `json:"LeadID"`
	ManagerID        *int    `json:"ManagerID"`
	MemberID         *int    `json:"MemberID"`
	CampaignID       *int    `json:"CampaignID"`
	CurrencyID       *int    `json:"CurrencyID"`
	Email            *string `json:"Email"`
	Phone            *string `json:"Phone"`
	IP               *string `json:"IP"`
	FirstName        *string `json:"FirstName"`
	LastName         *string `json:"LastName"`
	Gender           *string `json:"Gender"`
	FamilyStatus     *string `json:"FamilyStatus"`
	MaidenName       *string `json:"MaidenName"`
	Citizenship      *string `json:"Citizenship"`
	Country          *string `json:"Country"`
	City             *string `json:"City"`
	Zip              *string `json:"Zip"`
	Address1         *string `json:"Address1"`
	Address2         *string `json:"Address2"`
	StreetNumber     *string `json:"StreetNumber"`
	StreetName       *string `json:"StreetName"`
	Birthday         *string `json:"Birthday"`
	Status           *string `json:"Status"`
	DateCreated      *string `json:"DateCreated"`
	TimestampCreated *int    `json:"TimestampCreated"`
}

type ListRequest struct {
	SortBy string `json:"SortBy"`
	Value  string `json:"Value"`
}

type ManagerAssignBankDetailsToOfferRequest struct {
	OfferID       int `json:"OfferID"`
	BankDetailsID int `json:"BankDetailsID"`
}

type ManagerAssignInvestToOfferRequest struct {
	OfferID  int `json:"OfferID"`
	InvestID int `json:"InvestID"`
}

type ManagerAssignLeadToManagerRequest struct {
	LeadID    int `json:"LeadID"`
	ManagerID int `json:"ManagerID"`
}

type ManagerAssignManagerRequest struct {
	MemberID int `json:"MemberID"`
}

type ManagerAssignMemberToOfferRequest struct {
	OfferID  int `json:"OfferID"`
	MemberID int `json:"MemberID"`
}

type ManagerCreateAppointmentRequest struct {
	Type        *string `json:"Type"`
	Title       *string `json:"Title"`
	Description *string `json:"Description"`
	DateDue     *string `json:"DateDue"`
	Status      *string `json:"Status"`
	LeadID      *int    `json:"LeadID"`
}

type ManagerCreateBankDetailsRequest struct {
	Title                  string  `json:"Title"`
	BeneficiaryCompany     *string `json:"BeneficiaryCompany"`
	BeneficiaryFirstName   *string `json:"BeneficiaryFirstName"`
	BeneficiaryLastName    *string `json:"BeneficiaryLastName"`
	BeneficiaryCountry     *string `json:"BeneficiaryCountry"`
	BeneficiaryCity        *string `json:"BeneficiaryCity"`
	BeneficiaryZip         *string `json:"BeneficiaryZip"`
	BeneficiaryAddress     *string `json:"BeneficiaryAddress"`
	BankName               *string `json:"BankName"`
	BankBranch             *string `json:"BankBranch"`
	BankIfsc               *string `json:"BankIFSC"`
	BankBranchCountry      *string `json:"BankBranchCountry"`
	BankBranchCity         *string `json:"BankBranchCity"`
	BankBranchZip          *string `json:"BankBranchZip"`
	BankBranchAddress      *string `json:"BankBranchAddress"`
	BankAccountNumber      *string `json:"BankAccountNumber"`
	BankAccountType        *string `json:"BankAccountType"`
	BankRoutingNumber      *string `json:"BankRoutingNumber"`
	BankTransferCaption    *string `json:"BankTransferCaption"`
	BankIban               *string `json:"BankIBAN"`
	BankSwift              *string `json:"BankSWIFT"`
	BankSWIFTCorrespondent *string `json:"BankSWIFTCorrespondent"`
	BankBic                *string `json:"BankBIC"`
}

type ManagerCreateCampaignRequest struct {
	Title       *string `json:"Title"`
	Description *string `json:"Description"`
}

type ManagerCreateCategoryRequest struct {
	Title string `json:"Title"`
}

type ManagerCreateChecklistRequest struct {
	Title    *string `json:"Title"`
	Complete *bool   `json:"Complete"`
	Position *int    `json:"Position"`
	LeadID   *int    `json:"LeadID"`
}

type ManagerCreateCommentRequest struct {
	Content *string `json:"Content"`
	LeadID  *int    `json:"LeadID"`
}

type ManagerCreateContractRequest struct {
	Title      *string `json:"Title"`
	ContentRaw *string `json:"ContentRaw"`
}

type ManagerCreateCurrencyRequest struct {
	Title  string `json:"Title"`
	Symbol string `json:"Symbol"`
}

type ManagerCreateInterestRequest struct {
	OfferID      int    `json:"OfferID"`
	AmountFrom   string `json:"AmountFrom"`
	AmountTo     string `json:"AmountTo"`
	DurationFrom string `json:"DurationFrom"`
	DurationTo   string `json:"DurationTo"`
	Interest     string `json:"Interest"`
}

type ManagerCreateInvestRequest struct {
	CategoryID  int    `json:"CategoryID"`
	Title       string `json:"Title"`
	Subtitle    string `json:"Subtitle"`
	Description string `json:"Description"`
}

type ManagerCreateLeadRequest struct {
	ManagerID    *int    `json:"ManagerID"`
	MemberID     *int    `json:"MemberID"`
	CampaignID   *int    `json:"CampaignID"`
	CurrencyID   *int    `json:"CurrencyID"`
	Email        *string `json:"Email"`
	Phone        *string `json:"Phone"`
	IP           *string `json:"IP"`
	FirstName    *string `json:"FirstName"`
	LastName     *string `json:"LastName"`
	Gender       *string `json:"Gender"`
	FamilyStatus *string `json:"FamilyStatus"`
	MaidenName   *string `json:"MaidenName"`
	Citizenship  *string `json:"Citizenship"`
	Country      *string `json:"Country"`
	City         *string `json:"City"`
	Zip          *string `json:"Zip"`
	Address1     *string `json:"Address1"`
	Address2     *string `json:"Address2"`
	StreetNumber *string `json:"StreetNumber"`
	StreetName   *string `json:"StreetName"`
	Birthday     *string `json:"Birthday"`
	Status       *string `json:"Status"`
}

type ManagerCreateOfferRequest struct {
	InvestID      int    `json:"InvestID"`
	MemberID      int    `json:"MemberID"`
	CurrencyID    int    `json:"CurrencyID"`
	BankDetailsID int    `json:"BankDetailsID"`
	Title         string `json:"Title"`
}

type ManagerDealByContractIDRequest struct {
	OfferID    int `json:"OfferID"`
	ContractID int `json:"ContractID"`
}

type ManagerDuplicateAndAssignContractToOfferRequest struct {
	OfferID    int `json:"OfferID"`
	ContractID int `json:"ContractID"`
}

type ManagerDuplicateRequest struct {
	RecordID int `json:"RecordID"`
}

type ManagerEditAppointmentRequest struct {
	AppointmentID int     `json:"AppointmentID"`
	Type          *string `json:"Type"`
	Title         *string `json:"Title"`
	Description   *string `json:"Description"`
	DateDue       *string `json:"DateDue"`
	Status        *string `json:"Status"`
	LeadID        *int    `json:"LeadID"`
}

type ManagerEditBankDetailsRequest struct {
	BankDetailsID          int     `json:"BankDetailsID"`
	Title                  string  `json:"Title"`
	BeneficiaryCompany     *string `json:"BeneficiaryCompany"`
	BeneficiaryFirstName   *string `json:"BeneficiaryFirstName"`
	BeneficiaryLastName    *string `json:"BeneficiaryLastName"`
	BeneficiaryCountry     *string `json:"BeneficiaryCountry"`
	BeneficiaryCity        *string `json:"BeneficiaryCity"`
	BeneficiaryZip         *string `json:"BeneficiaryZip"`
	BeneficiaryAddress     *string `json:"BeneficiaryAddress"`
	BankName               *string `json:"BankName"`
	BankBranch             *string `json:"BankBranch"`
	BankIfsc               *string `json:"BankIFSC"`
	BankBranchCountry      *string `json:"BankBranchCountry"`
	BankBranchCity         *string `json:"BankBranchCity"`
	BankBranchZip          *string `json:"BankBranchZip"`
	BankBranchAddress      *string `json:"BankBranchAddress"`
	BankAccountNumber      *string `json:"BankAccountNumber"`
	BankAccountType        *string `json:"BankAccountType"`
	BankRoutingNumber      *string `json:"BankRoutingNumber"`
	BankTransferCaption    *string `json:"BankTransferCaption"`
	BankIban               *string `json:"BankIBAN"`
	BankSwift              *string `json:"BankSWIFT"`
	BankSWIFTCorrespondent *string `json:"BankSWIFTCorrespondent"`
	BankBic                *string `json:"BankBIC"`
}

type ManagerEditCampaignRequest struct {
	CampaignID  int     `json:"CampaignID"`
	Title       *string `json:"Title"`
	Description *string `json:"Description"`
}

type ManagerEditCategoryRequest struct {
	CategoryID int `json:"CategoryID"`
}

type ManagerEditChecklistRequest struct {
	ChecklistID int     `json:"ChecklistID"`
	Title       *string `json:"Title"`
	Complete    *bool   `json:"Complete"`
	Position    *int    `json:"Position"`
	LeadID      *int    `json:"LeadID"`
}

type ManagerEditCommentRequest struct {
	CommentID int     `json:"CommentID"`
	Content   *string `json:"Content"`
	LeadID    *int    `json:"LeadID"`
}

type ManagerEditContractRequest struct {
	ContractID int     `json:"ContractID"`
	Title      *string `json:"Title"`
	ContentRaw *string `json:"ContentRaw"`
}

type ManagerEditCurrencyRequest struct {
	CurrencyID int `json:"CurrencyID"`
}

type ManagerEditInvestRequest struct {
	InvestID    int    `json:"InvestID"`
	CategoryID  int    `json:"CategoryID"`
	Title       string `json:"Title"`
	Subtitle    string `json:"Subtitle"`
	Description string `json:"Description"`
}

type ManagerEditInvoiceRequest struct {
	InvoiceID int    `json:"InvoiceID"`
	Status    string `json:"Status"`
}

type ManagerEditLeadRequest struct {
	LeadID       int     `json:"LeadID"`
	ManagerID    *int    `json:"ManagerID"`
	MemberID     *int    `json:"MemberID"`
	CampaignID   *int    `json:"CampaignID"`
	CurrencyID   *int    `json:"CurrencyID"`
	Email        *string `json:"Email"`
	Phone        *string `json:"Phone"`
	IP           *string `json:"IP"`
	FirstName    *string `json:"FirstName"`
	LastName     *string `json:"LastName"`
	Gender       *string `json:"Gender"`
	FamilyStatus *string `json:"FamilyStatus"`
	MaidenName   *string `json:"MaidenName"`
	Citizenship  *string `json:"Citizenship"`
	Country      *string `json:"Country"`
	City         *string `json:"City"`
	Zip          *string `json:"Zip"`
	Address1     *string `json:"Address1"`
	Address2     *string `json:"Address2"`
	StreetNumber *string `json:"StreetNumber"`
	StreetName   *string `json:"StreetName"`
	Birthday     *string `json:"Birthday"`
	Status       *string `json:"Status"`
}

type ManagerEditMediaRequest struct {
	MediaID int    `json:"MediaID"`
	Title   string `json:"Title"`
}

type ManagerEditOfferRequest struct {
	OfferID    int    `json:"OfferID"`
	CurrencyID int    `json:"CurrencyID"`
	Title      string `json:"Title"`
}

type ManagerMediaByInvestIDRequest struct {
	RecordID int    `json:"RecordID"`
	Category string `json:"Category"`
}

type ManagerOffer struct {
	OfferID       int     `json:"OfferID"`
	MemberID      *int    `json:"MemberID"`
	InvestID      *int    `json:"InvestID"`
	CurrencyID    *int    `json:"CurrencyID"`
	BankDetailsID *int    `json:"BankDetailsID"`
	Title         *string `json:"Title"`
	Status        *string `json:"Status"`
}

type ManagerSearch struct {
	ManagerID int     `json:"ManagerID"`
	Title     *string `json:"Title"`
}

type Media struct {
	MediaID  int     `json:"MediaID"`
	MemberID *int    `json:"MemberID"`
	InvestID *int    `json:"InvestID"`
	URL      *string `json:"URL"`
	Title    *string `json:"Title"`
	Position *int    `json:"Position"`
	Filename *string `json:"Filename"`
	Category *string `json:"Category"`
	Created  *int    `json:"Created"`
}

type Member struct {
	MemberID           int     `json:"MemberID"`
	Email              *string `json:"Email"`
	ManagerID          *int    `json:"ManagerID"`
	IP                 *string `json:"IP"`
	FirstName          *string `json:"FirstName"`
	LastName           *string `json:"LastName"`
	Gender             *string `json:"Gender"`
	FamilyStatus       *string `json:"FamilyStatus"`
	MaidenName         *string `json:"MaidenName"`
	Citizenship        *string `json:"Citizenship"`
	Country            *string `json:"Country"`
	City               *string `json:"City"`
	Zip                *string `json:"Zip"`
	Address1           *string `json:"Address1"`
	Address2           *string `json:"Address2"`
	StreetNumber       *string `json:"StreetNumber"`
	StreetName         *string `json:"StreetName"`
	Image              *string `json:"Image"`
	Birthday           *string `json:"Birthday"`
	EmailNotifications *bool   `json:"EmailNotifications"`
	Phone              *string `json:"Phone"`
	Created            *int    `json:"Created"`
	Role               *int    `json:"Role"`
	CurrencyID         *int    `json:"CurrencyID"`
	Usd                *string `json:"USD"`
	Eur                *string `json:"EUR"`
	LeverageAllowed    *string `json:"LeverageAllowed"`
	StopLossAllowed    *string `json:"StopLossAllowed"`
	TakeProfitAllowed  *string `json:"TakeProfitAllowed"`
	Status             *string `json:"Status"`
	ManagerRole        *string `json:"ManagerRole"`
}

type MemberEmailUpdateRequest struct {
	Email string `json:"Email"`
}

type MemberPersonalUpdateRequest struct {
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
}

type MemberPhoneUpdateRequest struct {
	Phone string `json:"Phone"`
}

type Offer struct {
	OfferID       int       `json:"OfferID"`
	MemberID      *int      `json:"MemberID"`
	InvestID      *int      `json:"InvestID"`
	CurrencyID    *int      `json:"CurrencyID"`
	BankDetailsID *int      `json:"BankDetailsID"`
	Title         *string   `json:"Title"`
	Status        *string   `json:"Status"`
	Subtitle      *string   `json:"Subtitle"`
	Description   *string   `json:"Description"`
	Contract      *Contract `json:"Contract"`
	Faq           []*Faq    `json:"FAQ"`
}

type OfferGeneratePDFRequest struct {
	OfferID int `json:"OfferID"`
}

type OfferInitDealRequest struct {
	OfferID  int    `json:"OfferID"`
	Amount   string `json:"Amount"`
	Duration string `json:"Duration"`
}

type OfferPdf struct {
	URL string `json:"URL"`
}

type OfferPhoneVerifyRequest struct {
	OfferID int    `json:"OfferID"`
	Code    string `json:"Code"`
}

type OfferSignRequest struct {
	OfferID int    `json:"OfferID"`
	Image   string `json:"Image"`
}

type OfferSignResult struct {
	Status  bool    `json:"Status"`
	Message *string `json:"Message"`
	Timeout *int    `json:"Timeout"`
}

type PhoneVerifyRequest struct {
	Code   string `json:"Code"`
	Action string `json:"Action"`
}

type PhoneVerifyResponse struct {
	Timeout int `json:"Timeout"`
}

type RecordRequest struct {
	RecordID int `json:"RecordID"`
}

type ResetCompleteRequest struct {
	Action   string `json:"Action"`
	Method   string `json:"Method"`
	Hash     string `json:"Hash"`
	Code     string `json:"Code"`
	Password string `json:"Password"`
}

type ResetRequest struct {
	Email string `json:"Email"`
}

type Result struct {
	Status  bool    `json:"Status"`
	Message *string `json:"Message"`
}

type SearchRequest struct {
	Query string `json:"Query"`
}

type SignInRequest struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
}

type SignInResponse struct {
	Status  bool    `json:"Status"`
	Message *string `json:"Message"`
	Token   *string `json:"Token"`
}

type SignUpRequest struct {
	FirstName    string `json:"FirstName"`
	LastName     string `json:"LastName"`
	Birthday     string `json:"Birthday"`
	Citizenship  string `json:"Citizenship"`
	Gender       string `json:"Gender"`
	FamilyStatus string `json:"FamilyStatus"`
	MaidenName   string `json:"MaidenName"`
	Phone        string `json:"Phone"`
	Email        string `json:"Email"`
	Password     string `json:"Password"`
	Country      string `json:"Country"`
	City         string `json:"City"`
	Zip          string `json:"Zip"`
	StreetNumber string `json:"StreetNumber"`
	StreetName   string `json:"StreetName"`
}

type Tx struct {
	Txid              int     `json:"TXID"`
	MemberID          *int    `json:"MemberID"`
	Amount            *string `json:"Amount"`
	AmountNegative    *bool   `json:"AmountNegative"`
	CurrencyID        *int    `json:"CurrencyID"`
	Status            *string `json:"Status"`
	DateCreated       *string `json:"DateCreated"`
	DateComplete      *string `json:"DateComplete"`
	TimestampCreated  *int    `json:"TimestampCreated"`
	TimestampComplete *int    `json:"TimestampComplete"`
}

type Upload struct {
	UploadID int     `json:"UploadID"`
	MemberID *int    `json:"MemberID"`
	URL      *string `json:"URL"`
	Filename *string `json:"Filename"`
	Category *string `json:"Category"`
	Created  *int    `json:"Created"`
}

type ValidateFieldRequest struct {
	Field   string  `json:"Field"`
	Value   string  `json:"Value"`
	Type    *string `json:"Type"`
	Section *string `json:"Section"`
	Path    *string `json:"Path"`
}

type ValudationStatus struct {
	Status  bool   `json:"Status"`
	Message string `json:"Message"`
}

type Verify struct {
	Method *string `json:"method"`
	Hash   string  `json:"hash"`
	Code   string  `json:"code"`
}

type VerifyRequest struct {
	Action string `json:"Action"`
	Method string `json:"Method"`
	Hash   string `json:"Hash"`
	Code   string `json:"Code"`
}

type VerifyResendRequest struct {
	Email string `json:"Email"`
}

type VerifyResendResponse struct {
	Status  bool    `json:"Status"`
	Message *string `json:"Message"`
	Timeout *int    `json:"Timeout"`
}

type VerifyResponse struct {
	Status  bool    `json:"Status"`
	Message *string `json:"Message"`
	Token   *string `json:"Token"`
}

type FamilyStatus string

const (
	FamilyStatusNo       FamilyStatus = "no"
	FamilyStatusMarried  FamilyStatus = "married"
	FamilyStatusDivorced FamilyStatus = "divorced"
	FamilyStatusWidowed  FamilyStatus = "widowed"
)

var AllFamilyStatus = []FamilyStatus{
	FamilyStatusNo,
	FamilyStatusMarried,
	FamilyStatusDivorced,
	FamilyStatusWidowed,
}

func (e FamilyStatus) IsValid() bool {
	switch e {
	case FamilyStatusNo, FamilyStatusMarried, FamilyStatusDivorced, FamilyStatusWidowed:
		return true
	}
	return false
}

func (e FamilyStatus) String() string {
	return string(e)
}

func (e *FamilyStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FamilyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FamilyStatus", str)
	}
	return nil
}

func (e FamilyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Gender string

const (
	GenderM Gender = "m"
	GenderF Gender = "f"
)

var AllGender = []Gender{
	GenderM,
	GenderF,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderM, GenderF:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Status string

const (
	StatusPending  Status = "PENDING"
	StatusProgress Status = "PROGRESS"
	StatusFailed   Status = "FAILED"
	StatusComplete Status = "COMPLETE"
)

var AllStatus = []Status{
	StatusPending,
	StatusProgress,
	StatusFailed,
	StatusComplete,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusPending, StatusProgress, StatusFailed, StatusComplete:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
